//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class SplatMapComparator
	{
		float _rangeMax;
		float _rangeMin;
		float _rangeBlend;
		
		public SplatMapComparator (float rangeMax, float rangeMin, float rangeBlend)
		{
			_rangeMax = rangeMax;
			_rangeMin = rangeMin;
			_rangeBlend = rangeBlend;
		}
		
		
		public float calculateValue(float input)
		{
			float outputValue = 1.0f;
			float modifier = 1.0f;
			
			if(input >= _rangeMin && input <= _rangeMax)
			{
				outputValue = 1.0f;
			}
			else if(input >= _rangeMin - _rangeBlend && input < _rangeMin)
			{
				float normalizedBlend = (_rangeBlend - Mathf.Abs(input - (_rangeMin - _rangeBlend))) / _rangeBlend;
			
				modifier = 1 - normalizedBlend;
				outputValue = 1.0f;
			}
			else if(input <= _rangeMax + _rangeBlend && input > _rangeMax)
			{
				float normalizedBlend = (_rangeBlend - Mathf.Abs(input - (_rangeMax + _rangeBlend))) / _rangeBlend;
				
				modifier = 1 - normalizedBlend;
				outputValue = 1.0f;
			}
			else
			{
				outputValue = 0.0f;
			}
			
			return outputValue * modifier;
		}
	}
}

